language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install

script: bin/phpunit
