language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - sudo pecl install amqp
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install

script: bin/phpunit