language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - if [[ $TRAVIS_PHP_VERSION = 'hhvm' ]]; then echo "extension = amqp.so" >> /etc/hhvm/php.ini  fi;
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini fi;
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install

script: bin/phpunit